FROM node:12
WORKDIR /app

COPY package.json .
COPY tsconfig.json .
COPY package-lock.json .
COPY .eslintrc .
COPY jest.config.js .
COPY nx.json .
COPY workspace.json .
RUN npm ci -S
COPY apps ./apps
COPY libs ./libs
COPY .git ./.git
