FROM node:14 AS nx-tuto-base
WORKDIR /app

COPY package.json .
COPY tsconfig.json .
COPY package-lock.json .
COPY .eslintrc .
COPY jest.config.js .
COPY nx.json .
COPY workspace.json .

RUN npm ci -S
COPY apps ./apps
COPY libs ./libs
RUN npm run build -S

# ---------------

FROM nginx:alpine AS nx-tuto-front
COPY nginx.conf /etc/nginx/nginx.conf
WORKDIR /usr/share/nginx/html
COPY --from=nx-tuto-base /app/dist/apps/front .

