FROM node:12 AS nx-tuto-base
WORKDIR /app

COPY package.json .
COPY tsconfig.json .
COPY package-lock.json .
COPY .eslintrc .
COPY jest.config.js .
COPY nx.json .
COPY workspace.json .
RUN npm ci -S
COPY apps ./apps
COPY libs ./libs
RUN npm run affected:lint -- --base=origin/master
RUN npm run affected:test -- --base=origin/master
RUN npm run affected:build -- --base=origin/master
CMD ["node", "main.js"]

FROM nginx:alpine AS nx-tuto-front
COPY nginx.conf /etc/nginx/nginx.conf
WORKDIR /usr/share/nginx/html
COPY --from=nx-tuto-base /app/dist/apps/front .

FROM node:14 AS nx-tuto-api
#EXPOSE 3333
WORKDIR /app
COPY package.json .
COPY package-lock.json .
RUN npm ci --only=production -S
COPY --from=nx-tuto-base /app/dist/apps/api .
CMD ["node", "main.js"]
